### ISSUE TITLE
Inquiry for rendering horse.

### ISSUE THREAD

**Issue by JangBoo** [panda2ici/Computer-Graphics#1]
Hi,

I run your code A2. It complies but it renders the plane with texture but it didn't run the horse figure.

Do you know how I can make it work?

Thanks!

**Comment by lingt-xyz** [comment]
Hi, sorry I am not able to recall what I have done in the assignments.
One thing I need to mention is I used Code::Blocks instead of Visual Studio to code, and you can see the Code::Blocks configuration file in the corresponding folder.
So the code is supposed to be runnable on a lab computer using Code::Blocks.

That's all I know at this moment.

**Comment by JangBoo** [comment]
Thanks it works
